# Generated by Django 5.1.6 on 2025-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l_f', '0003_remove_lostitem_name_lostitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
